### ISSUE TITLE
[Feature Request] Ability to change the positions of the plot components

### ISSUE THREAD

**Issue by iandol** [jorvlan/raincloudplots#10]
In both https://github.com/RainCloudPlots/RainCloudPlots and https://github.com/jorvlan/open-visualizations examples are show where for example, the density plot is "mirrored" for the two groups (leftwards for first group, rightwards for second). Or they are overlapping etc. 

It would be great if we could pass some parameters to allow us to change the layout like this for the plots. Note I am not an R user, but a MATLAB users who wanys to make some more flexible plots and this package is much easier to use than the lower-level code.

Thanks for a nice package!

**Comment by jorvlan** [comment]
thanks for your feedback! we will take it in consideration

**Comment by jorvlan** [comment]
Update: we are working on a revised R package that is based on ggplot2 and allows you to pass all ggplot parameters into our ```geom_rain()``` functionality. Should be up an running in a couple of months, so please stay tuned!

**Comment by iandol** [comment]
Awesome, thank you!!!
