### ISSUE TITLE
How to fed the dataset of N x 4, where n is the participants and 4 represent columns (T1, T2, T3, and T4)

### ISSUE THREAD

**Issue by nileshkrsahu** [jorvlan/raincloudplots#13]
Hi Jorvlan,

How to draw the raincloud plot for, say, n participants' self-report (range - 1 to 5) taken at four different timestamps, say T1, T2, T3, and T4. I was unable to understand how to create the data to be fed into this library since I wanted to track the changes in self-report for each participant.

**Comment by jorvlan** [comment]
Hey!

The current capabilities of the [raincloudplots](https://github.com/jorvlan/raincloudplots) does not allow you to specify more than 3 timepoints. We do, however, have developed an updated and better version of this package which is named: [ggrain](https://github.com/njudd/ggrain) which allows you to specify an `n` number of timepoints. Please visit that page and see whether you can create the plot you want! 

Best, Jordy
