### ISSUE TITLE
Option to add legend? 

### ISSUE THREAD

**Issue by fabiennevr** [jorvlan/raincloudplots#3]
Hi @jorvlan 

Your code worked beautifully, I'm glad with the amazing plot. There is one question I have; is there an option to add a legend to the plot as well? I looked at your code and it doesn't seem to include one. I also tried to add a legend via the legend() command, but that didn't work out either. 

Best!
Fabienne

**Comment by jorvlan** [comment]
Hi @fabiennevr

Thanks for your support and feedback!
Currently, there is no built-in function to add a legend.
However, you can add a legend manually for e.g., with `theme()` and then add `scale_fill_manual` and `scale_color_manual`. 
But there are other ways to do it, for e.g. search on stackoverflow.com or community.rstudio.com
