### ISSUE TITLE
Issues with the installation of the package

### ISSUE THREAD

**Issue by jukicivan** [jorvlan/raincloudplots#4]
Hey there,

I simply can't install the package while using the following:

```
if (!require(remotes)) {
    install.packages("remotes")
}
remotes::install_github('jorvlan/raincloudplots')

library(raincloudplots)
```

I get "unknown package" error.

**Comment by jorvlan** [comment]
Can you show me the error message?

I just uninstalled the package and installed it again, which worked fine.

**Comment by dikiprawisuda** [comment]
Hi @jorvlan,

I do not know if this is related, but I also got an error when use {dtupdate} package to update non-CRAN packages. 
```
Warning message:
In read.dcf(url_con, fields = "Version") :
  cannot open URL 'https://raw.githubusercontent.com/jorvlan/raincloudplots/master/DESCRIPTION': HTTP status was '404 Not Found'
```
But the package is usable, I can also reinstall it.

**Comment by jorvlan** [comment]
@dikiprawisuda thanks for your feedback.
I haven't used {dtupdate} myself, so my guess would be to update our package manually (if needed?) There only has been one update so far (0.1.0 > 0.2.0).

**Comment by jukicivan** [comment]
I apologise for a very slow response. Please find the reprex below:

``` r
if (!require(remotes)) {
  install.packages("remotes")
}
#> Loading required package: remotes
remotes::install_github('jorvlan/raincloudplots')
#> Error: Failed to install 'unknown package' from GitHub:
#>   HTTP error 404.
#>   Not Found
#> 
#>   Did you spell the repo owner (`jorvlan`) and repo name (`raincloudplots`) correctly?
#>   - If spelling is correct, check that you have the required permissions to access the repo.

library(raincloudplots)
#> Error in library(raincloudplots): there is no package called 'raincloudplots'
```

<sup>Created on 2021-03-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jorvlan** [comment]
@jukicivan Can you check the following options:

- make sure you have `devtools` installed
- make sure you have the latest version of `remotes` installed (suggested by @niklasjohannes , below)
- update R to the newest version 4.0.4
- try `remotes::install_github` with a different R-package and see if this works.
- install the newest version of raincloudplots 0.2.0

**Comment by niklasjohannes** [comment]
I had the same problem. Had to update the `remotes` package first, then installation went fine.
