### ISSUE TITLE
Uneven size of arrays

### ISSUE THREAD

**Issue by Chandrima-04** [jorvlan/raincloudplots#6]
I have been trying to create a 2*3 raincloud, but my classes have uneven sizes. The class sizes are:
7S-Shallow -> 5 rows
G-Shallow -> 8 rows
G-Deep -> 7 rows

``` df_2x3 <- data_2x2(
  array_1 = meta_taxa$alpha_shannon[(meta_taxa$Loc_Depth=="7S-Shallow")],
  array_2 = meta_taxa$alpha_simpson[(meta_taxa$Loc_Depth=="7S-Shallow")],
  array_3 = meta_taxa$alpha_shannon[(meta_taxa$Loc_Depth=="G-Shallow")],
  array_4 = meta_taxa$alpha_simpson[(meta_taxa$Loc_Depth=="G-Shallow")],
  array_5 = meta_taxa$alpha_shannon[(meta_taxa$Loc_Depth=="G-Deep")],
  array_6 = meta_taxa$alpha_simpson[(meta_taxa$Loc_Depth=="G-Deep")],
  labels = (c('Shannon','Simpson' )),
  jit_distance = .05,
  jit_seed = 321)

raincloud_2x3_repmes(
  data = df_2x3, 
  colors = (c("lightseagreen","darkolivegreen4","coral1","indianred4","lightpink1","palevioletred1")), 
  fills = (c("lightseagreen","darkolivegreen4","coral1","indianred4","lightpink1","palevioletred1")), 
  size = 1, 
  alpha = .6, 
  ort = 'v') +
scale_x_continuous(breaks=c(1,2,3), labels=c("7S-Shallow", "G-Shallow", "G-Deep")) +
  scale_y_continuous(breaks=c(1,2), labels=c("Simpson", "Shannon")) +
  xlab("Time") + 
  ylab("Diversity Score") +
  theme_classic() 
```

This is the error I am getting
`Error in data.frame(y_axis = c(array_1, array_2, array_3, array_4, array_5, : arguments imply differing number of rows: 46, 48, 16`

What would your suggestion be for this issue?

**Comment by Chandrima-04** [comment]
When I used the top 4 arrays, the data frame formed seems to be skipping row number:
<img width="1440" alt="Screen Shot 2021-06-09 at 10 43 16 AM" src="https://user-images.githubusercontent.com/9072403/121297258-0e0de600-c8c0-11eb-9844-5653a25903e2.png">

**Comment by jorvlan** [comment]
Hi, thanks for your feedback and code example.
I just realized there is an argument missing for array_5 & array_6 with unequal array sizes.
I will try to look into this when I find the time.


What you could try to do in the meantime is run the following to create your `data.frame`.

```r
data_2x2 <- data.frame(y_axis = c(array_1, array_2, array_3, array_4, array_5, array_6),
                       x_axis = rep(c(1,1.01,2,2.01,3,3.01), each=n),
                       id = factor(rep(1:n,2)),
                       group = rep(c(labels[1], labels[2]), each=n))
```
Then omit the NA's (unequal rows) with `na.omit` (make sure to install the `stats` package.
```r
if (any(is.na(data_2x2)))
  data_2x2 <- stats::na.omit(data_2x2)
```
I hope this resolves the unequal rows issue.

**Comment by Chandrima-04** [comment]
It shouldn't be much difficult, you have a line looking for size and you put everything as "n"
But if you just remove the constraint, the raincloudplots will be way more usable!!
Btw, awesome work! This visualization looks absolutely fantastic!
I used a shortcut to create my df based on your code:

`set.seed(321)
#df_2x3 <- data.frame(matrix(ncol = 4, nrow = 0))
#x <- c("y_axis", "x_axis", "id", "group")
#colnames(df_2x3) <- x
y_axis <- c(meta_taxa$alpha_shannon[(meta_taxa$Loc_Depth=="7S-Shallow")], meta_taxa$alpha_simpson[(meta_taxa$Loc_Depth=="7S-Shallow")], meta_taxa$alpha_shannon[(meta_taxa$Loc_Depth=="G-Shallow")], meta_taxa$alpha_simpson[(meta_taxa$Loc_Depth=="G-Shallow")],
meta_taxa$alpha_shannon[(meta_taxa$Loc_Depth=="G-Deep")], 
meta_taxa$alpha_simpson[(meta_taxa$Loc_Depth=="G-Deep")])
x_axis <- c(rep(1.0, 5), rep(1.01, 5), rep(2.0, 8), rep(2.01, 8), rep(3.0, 7), rep(3.01, 7))
id <- c(factor(rep(1:5,2)), factor(rep(1:8,2)), factor(rep(1:7,2)))
group <- c(rep("Shannon",5), rep("Simpson",5), rep("Shannon",8), rep("Simpson",8), rep("Shannon",7), rep("Simpson",7)) 
jit <- jitter(x_axis, amount = 0.05)
df_2x3 <- data.frame(y_axis, x_axis, id, group, jit)
`
