### ISSUE TITLE
CRAN release 

### ISSUE THREAD

**Issue by liutiming** [jorvlan/raincloudplots#7]
Thanks for this awesome package! It will be helpful to publish it on CRAN as well, because some trusted research environment only allows internet access to very few IP addresses (CRAN accessible but GitHub not accessible)

**Comment by jorvlan** [comment]
Hi, thanks for the suggestion. We want to publish this package on CRAN, but it will need some improvements and extensions first. Hopefully, this can be done in the near future. We will let you & others know when it will be updated & uploaded. On behalf of the team. Best, Jordy
