### ISSUE TITLE
X axis label positioning

### ISSUE THREAD

**Issue by merrlog** [jorvlan/raincloudplots#9]
Is there a way to move the x-axis labels to centered under the density or between the box plot and density regions? Specifically in the raincloud_1_v example in the readme.  It seems like the positioning of "pre" and "post" are different in the other examples, but I cannot figure out how to adjust them.
thanks

**Comment by jorvlan** [comment]
repositioning of labels should be possible.
Maybe try to adjust and tweek around with 
```r
scale_x_continuous(breaks=c(1,2,3), labels=c("T-1", "T-2", "T-3"), limits=c(0, 4)) +
```

**Comment by merrlog** [comment]
Ok thanks so much for the response!
